//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aqueduct.SitecoreLib.Examples.SampleApplication.Web.Controls.Widgets
{


    public partial class FacebookWidgetControl
    {
    }
}
